// Code generated by ObjectBox; DO NOT EDIT.

package model

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(5)

	model.RegisterBinding(EntryBinding)
	model.RegisterBinding(DailyBinding)
	model.LastEntityId(2, 6434397660819005171)
	model.LastIndexId(1, 6103478220675169153)

	return model
}
